common: Fix check for factory
When running a command that requires a factory such as `fioctl targets
list`, you'd see:

 ERROR: Required flag "factory" not set

This change checks for the login first (which might set the factory) to
give the user a more accurate reponse.

Signed-off-by: Andy Doan <andy@foundries.io>